[tool.poetry]
name = "mlfin"
version = "0.0.1"
description = "Using RL to trade"
authors = ["perjonasam"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^0"
tensortrade = "^0.2.0-rc.0"
jupyter = "^1.0.0"
ccxt = "^1.30.85"
tensorflow = "^2.2.0"
stochastic = "^0.4.0"
matplotlib = "^3.2.2"
plotly = "^4.8.2"
ipython = "^7.16.1"
stable-baselines = "^2.10.0"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
