action_strategy:
    n_value_bins: 4  # amount bins for buy and sell each (hold has 1)

data_params:
  data_n_timesteps: 10  # number of timesteps passed as part of value timeseries
  n_portfolio_features: 3  # See env for usage
  ti_nan_timesteps: 199  # Set by the slowest lagging ti. Count nans on preprocessed df to know number.

trading_params:
  initial_account_balance: 10000  # USD
  commission: 0.2  # in %. 0.1-0.5 typical
  max_slippage: 0  # in %. 2-3 typical

policy:
  network: 'MlpPolicy'  # 'MlpPolicy', 'MlpLstmPolicy', 'MlpLnLstmPolicy'. NOTE: LSTM requires more code changes

reward:
  strategy: RiskAdjustedReturns(return_algorithm='sortino')
  calculation_timesteps: 100000

# Read relevant gotcha in README.md
input_data:
  asset: 'BTCUSD'
  source: 'Bitstamp'  # Bitstamp runs up until today
  tempres: '1s'  # n[s, m, h, d]

train_predict:
  # These will set the starting timesteps in reset. They are serial timesteps, independent of n_cpu
  train_timesteps: 1500  # Will be downsized to even multiple of n_steps (default 128)
  predict_timesteps: 250

monitoring:
  tensorboard:
    folder: 'data/monitoring/tensorboard'

benchmarks:
  strategies: [buy_and_hold, rsi_divergence, sma_crossover]  # Check env.trade.Benchmarks for available benchmarks

random_seed: 42
n_cpu: 8  # cores really. Will affect memory consumed (not shared data)