action_strategy:
    n_value_bins: 4  # amount bins for buy and sell each (hold has 1)

data_params:
  data_n_timesteps: 10  # number of timesteps passed as part of value timeseries
  n_nonprice_features: 3

policy:
  network: 'MlpPolicy'  # available: 'MlpPolicy', 'MlpLstmPolicy', 'MlpLnLstmPolicy'

input_data:
  asset: 'BTCUSD'
  source: 'Coinbase'
  tempres: '1m'

train_predict:
  train_timesteps: 3000  # These will set the starting timesteps in reset
  predict_timesteps: 500  # These will set the starting timesteps in reset

monitoring:
  tensorboard:
    folder: 'data/monitoring/tensorboard'

random_seed: 42