action_strategy:
    n_value_bins: 4  # amount bins for buy and sell each (hold has 1)

data_params:
  data_n_timesteps: 10  # number of timesteps passed as part of value timeseries
  n_portfolio_features: 3
  ti_nan_timesteps: 33  # Set by the slowest lagging ti. Count nans on preprocessed df to know number.

trading_params:
  initial_account_balance: 10000  # USD
  commission: 0  # in %
  max_slippage: 0  # in %

policy:
  network: 'MlpPolicy'  # available: 'MlpPolicy', 'MlpLstmPolicy', 'MlpLnLstmPolicy'. NOTE: LSTM requires more code changes

# Relevant gotcha in README.md
input_data:
  asset: 'BTCUSD'
  source: 'Coinbase'
  tempres: '1s'  # n[s, m, h, d]

train_predict:
  train_timesteps: 3000  # These will set the starting timesteps in reset
  predict_timesteps: 500  # These will set the starting timesteps in reset

monitoring:
  tensorboard:
    folder: 'data/monitoring/tensorboard'

benchmarks: 
  render: True
  strategies: [buy_and_hold, rsi_divergence, sma_crossover]  # Check env.trade.Benchmarks for available benchmarks

random_seed: 42