reward_strategy:
  cumulative_reward: True

action_strategy:
    n_value_bins: 4  # bins for buy and sell each (hold has 1)

data_n_timesteps: 10  # number of timesteps passed as part of value timeseries

n_nonprice_features: 3

input_data:
  asset: 'BTCUSD'
  source: 'Coinbase'
  tempres: '1h'

train_test:
  test_timesteps: 6000
  test_ratio: 0.3

monitoring:
  tensorboard:
    folder: 'data/monitoring/tensorboard'

  